### ISSUE TITLE
Upper - Texture issue

### ISSUE THREAD

**Issue by Kowagatte** [Kowagatte/Netherite#2]
__Issue:__
Upper - Texture upside down

__Description__
The texture for the upper is upside down, duplicating and flipping the textures for the minecraft hopper would fix this.
Need to fix textures:
   * "top": "block/hopper_top",
   * "side": "block/hopper_outside",
   * "inside": "block/hopper_inside"

__How to reproduce:__
Look at a upper.

__Version:__
0.1.0

**Comment by Kowagatte** [comment]
Flipping the textures vertically does not solve this issue, it actually makes the side pointing uppers look like regular uppers and makes regular uppers look like side pointing uppers. No idea how to fix this right now, if anyone knows how just chime in.

**Comment by Twitch1g88** [comment]
[upper_side.zip](https://github.com/Kowagatte/Netherite/files/5455504/upper_side.zip)
